### PR TITLE
Feature private event

### PR DESCRIPTION
**Pull request by pipe2442**
Project: Associations 

In this project we:

- Created rails app with users, events and attendances controllers and models.
- Created basic log in and user registration with no password just email.
- Created associations between models to save correct information for events and user attendances on database.
- Created all the MVC structure for our up and updated views with styles and project requirements to display 
attendances, past and future events.
- Added correct unit testing with Rspec and Capybara.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Felipe Angulo Torres & Pacifique Linjanja** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] List of upcoming and previously attended events (in users show) isn't working properly, it should only show the upcoming and previous attendances is the logged-in user.

### OPTIONAL 

- [x] The select user in attendances/new seems unnecessary, you might consider removing it.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by pipe2442** [comment]
Hi, @andresporras3423 All the changes where made thanks for the review!!!

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
## Hello, @pipe2442 and @pacyL2K19! You guys have done a great job. The application appears to be remarkable. Nice work implementing the changes that the previous TSE requested. Congratulations and good luck.

**Comment by pipe2442** [comment]
Thanks!!!! @smcommits

**Pull request merged**
